name    'puppet-rhn_management'
version '0.1.0'
source 'git://github.com/strider/puppet-rhn_management.git'
author 'Gael Chamoulaud <gchamoul@redhat.com>'
license 'Apache License, Version 2.0'
summary 'RHN Management providers for Puppet'
description 'This module provides Custom Providers for Red Hat Network Registering.'
project_page 'https://github.com/strider/puppet-rhn_management_ks'
dependency 'adrien/boolean', '>=0.9.0'
